AllCops:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/*'
    - 'bin/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false
